### ISSUE TITLE
Examples of authentication, read, and write

### ISSUE THREAD

**Issue by jakemauer** [jmerriweather/nerves_io_pn532#1]
Hi there! I'm embarking on an Elixir project that uses a PN532 board from Adafruit and with help from a friend I've actually got basic reading of my Mifare card's ID happening in my Elixir app. However I'm totally lost when it comes to reading and writing data from/to the card. I know you probably haven't looked at or thought about this code for years, but I was wondering if you could help me out with some examples for reading and writing data to a card. I would be happy to write up more thorough documentation as a PR once I can get the basics working. 

Thanks for writing this library, hope to hear from you soon.

**Comment by jmerriweather** [comment]
Hey Jake, 

Thanks for the comments. Unfortunately there are some issues with this library, its only really good at a quick demo.

Good news is that I wrote another library with the things I learnt from this one. I haven't made it public yet as I wasn't sure on the level of abstraction I wanted but it is a lot better than this library so might as well release it.

I've also got a project that is using this new library but I probably wont make that public, I'll extract out the useful bits though to show how to use it

I'll post in this issue with the new repo once its released

Cheers,
Jonathan

**Comment by jakemauer** [comment]
That's awesome! Can't wait to see the new library. Thanks again for sharing your work.

**Comment by jmerriweather** [comment]
I've just published a version of the other library here: https://github.com/jmerriweather/pn532

**Comment by jakemauer** [comment]
Woohoo! Thank you! I'll dig in this weekend.
